### PR TITLE
Update Kopernicus.version

### PR DESCRIPTION
**Pull request by drake127**
Just .version, need to also update links

### CODE REVIEW

**Comment by R-T-B** [comment]
I don't plan to CKAN index this so that version file is irrelevant.  We will have it up to date on stable releases, of course.

Thanks for watching out, anyways.  We should probably remove that file from my tree.

**Comment by drake127** [comment]
Fair enough, I am just little confused about branching. If you delete it here, you'd have to restore it in stable tree after merge. I don't know your Git flow though.

**Comment by 7ranceaddic7** [comment]
There should be one there already. That is the file that will be updated upon release.

**Comment by R-T-B** [comment]
yes, that is the plan.

**Pull request closed without merging**
