### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by democat3457**
tbh dunno why it has such a long commit history, there was probably a rebase somewhere

### CODE REVIEW

**Comment by democat3457** [comment]
oh i know why but its not fun to fix on web client

**Comment by democat3457** [comment]
the commits are going to have to be cherrypicked manually onto the dev branch, which is unfortunately not possible on web client

**Comment by R-T-B** [comment]
Ah, take your time.  It's cool.  My workflow starts in bleeding edge and I think that's what's making it upset.

**Comment by R-T-B** [comment]
I can manage the needed cherrypicking manually if you don't mind.  Oh wait, I'm the only one that can, aren't I?  Lol  I was waiting on you.

**Pull request merged**
